services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - '5678:5678'
    environment:
      - NODE_ENV=development
      - N8N_PORT=5678
      - N8N_TUNNEL=false
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_LOG_LEVEL=info
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - ./_dev/custom:/home/node/.n8n/custom:rw
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
